In [1]:
import scanpy as sc 
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.metrics import adjusted_rand_score
from sklearn.decomposition import PCA

import scipy.sparse as sp 
import warnings

warnings.filterwarnings("ignore")

import os
import ctypes
import sys

# 1. 先设置 R_HOME
os.environ["R_HOME"] = "/home/pxy/miniconda3/envs/r40/lib/R"

# 2. 【核心黑科技】手动加载 R 的动态库
# 这步操作等同于在终端里设置 LD_LIBRARY_PATH，专门解决 VS Code 找不到库的问题
try:
    # 这是 R 的核心库路径
    libR_path = "/home/pxy/miniconda3/envs/r40/lib/R/lib/libR.so"
    # 强制加载进内存
    ctypes.CDLL(libR_path, mode=ctypes.RTLD_GLOBAL)
    print("✅ 成功强制加载 libR.so")
except OSError as e:
    print(f"❌ 加载失败: {e}")

# 3. 然后再导入其他包
sys.path.append("..") 

import spCLUE
import rpy2.robjects as robjects
print("R 环境路径:", robjects.r['R.home']()[0])

spCLUE.fix_seed(0)

# 定义DLPFC数据集的12个切片ID
slice_ids = [
    "151507", "151508", "151509", "151510",
    "151669", "151670", "151671", "151672",
    "151673", "151674", "151675", "151676"
]

# 用于存储每个切片的ARI结果
ari_results = []

# 数据路径（请根据实际情况确认路径是否正确）
data_dir = '/home/pxy/home/pxy/data/DLPFC/st/'

# 【新增】创建保存图片的文件夹
figures_dir = "figures_test"
if not os.path.exists(figures_dir):
    os.makedirs(figures_dir)
    print(f"Created directory: {figures_dir}")

print(f"Start processing {len(slice_ids)} slices...")

for sample_name in slice_ids:
    print(f"\n{'='*20} Processing Sample: {sample_name} {'='*20}")
    
    # 1. 设置簇的数量 (根据DLPFC数据集的已知Ground Truth)
    # 151669-151672 通常只有5层，其他切片为7层
    if sample_name in ["151669", "151670", "151671", "151672"]:
        n_clusters = 5
    else:
        n_clusters = 7
    
    try:
        # 2. 加载数据
        # 使用 read_visium 加载数据，路径拼接逻辑参考原文件
        adata = sc.read_visium(data_dir + sample_name)
        adata.var_names_make_unique()
        
        # 加载元数据 (Ground Truth)
        meta = pd.read_csv(data_dir + sample_name + "/metadata.tsv", sep="\t")
        meta = meta.set_index("barcode")
        adata.obs["Region"] = meta.loc[adata.obs_names, "layer_guess_reordered"]
        
        # 3. 数据预处理与构图
        # 原文件 Cell 6 的逻辑
        # adata = spCLUE.preprocess(adata)
        # adata.obsm["X_pca"] = PCA(n_components=200, random_state=0).fit_transform(adata.X)
        
        # g_spatial = spCLUE.prepare_graph(adata, "spatial", n_neighbors=6)
        # g_expr = spCLUE.prepare_graph(adata, "expr", metric="euclidean", n_neighbors=8)
        from spCLUE.preprocess import (
            prepare_euclidean_graph, 
            prepare_cosine_graph, 
            prepare_fused_graph
        )

        # 1. 数据预处理
        adata = spCLUE.preprocess(adata, hvgNumber=3000)

        # 2. 构建三个视图的图
        adj_s, g_spatial = prepare_euclidean_graph(adata,)
        adj_f, g_feature = prepare_cosine_graph(adata, k=14)
        g_combined = prepare_fused_graph(adj_s, adj_f)

        # 3. 准备图字典
        graph_dict = {
            "spatial": g_spatial,
            "feature": g_feature,
            "combined": g_combined,
        }
        use_zinb = True
        
        # 4. 模型初始化与训练
        # 原文件 Cell 8 的逻辑
        # 注意：这里将 n_clusters 参数改为动态变量，与当前切片保持一致
        # spCLUE_model = spCLUE.spCLUE(adata.obsm["X_pca"], graph_dict, n_clusters,
                                    # )
        # _, adata.obsm["spCLUE"], att_beta = spCLUE_model.train()
        import scipy.sparse as sp

        input_x = adata.X
        if sp.issparse(input_x):
            input_x = input_x.toarray() # 将稀疏矩阵转为普通的 numpy array
        if "raw_count" in graph_dict and sp.issparse(graph_dict["raw_count"]):
            graph_dict["raw_count"] = graph_dict["raw_count"].toarray()
        spCLUE_model = spCLUE.spCLUE(
            input_data=input_x,
            graph_dict=graph_dict,
            n_clusters=n_clusters,
            lambda_ccr=5.0,  # CCR损失权重
            use_zinb=True,  # 是否使用ZINB解码器
            # kappa=0.1,
            beta=0.0,
            gamma=1.0,
        )
        _, adata.obsm["spCLUE"], attention_weights = spCLUE_model.train()
        
        # 5. 聚类
        # 原文件 Cell 10 的逻辑
        refinement = True
        cluster_method = "mclust"
        spCLUE.clustering(
            adata,
            n_clusters,
            key="spCLUE",
            refinement=refinement,
            cluster_methods=cluster_method,
        )
        
        # 6. 计算 ARI
        # 原文件 Cell 12 的逻辑
        # 过滤掉 Ground Truth 为 NA 的区域
        adata_valid = adata[adata.obs.Region.notna()]
        ARI = adjusted_rand_score(adata_valid.obs["Region"], adata_valid.obs["mclust_refined"])
        
        print(f"Sample {sample_name} ARI: {ARI:.8f}")
        ari_results.append(ARI)

        # 绘图：show=False 防止直接显示，便于后续保存
        adata.obs["spCLUE"] = adata.obs["mclust_refined"]
        sc.pl.spatial(
            adata, 
            color=["Region", "spCLUE"], 
            title=["Manual Annotation", f"spCLUE (ARI={round(ARI, 2)})"],
            show=False 
        )
        
        # 保存路径
        save_path = os.path.join(figures_dir, f"{sample_name}.png")
        
        # 保存图片 (bbox_inches='tight' 去除多余白边, dpi=300 保证清晰度)
        plt.savefig(save_path, bbox_inches='tight', dpi=300)
        
        # 关闭当前图形，释放内存 (在循环中非常重要，否则内存会爆)
        plt.close()
        
        print(f"Figure saved to: {save_path}")
        
    except Exception as e:
        print(f"Error processing sample {sample_name}: {e}")

# 7. 输出最终统计结果
print(f"\n{'='*20} Final Results {'='*20}")
if ari_results:
    mean_ari = np.mean(ari_results)
    median_ari = np.median(ari_results)
    print(f"ARI per slice: {[round(x, 5) for x in ari_results]}")
    print(f"Mean ARI: {mean_ari:.4f}")
    print(f"Median ARI: {median_ari:.4f}")
else:
    print("No ARI results collected.")

✅ 成功强制加载 libR.so
R 环境路径: /home/pxy/miniconda3/envs/r40/lib/R
Start processing 12 slices...

==================== Processing Sample: 151507 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 41%|████      | 103/250 [00:04<00:05, 27.45it/s]

epoch 100: ARI=-0.0051, CCR=0.5005, CLU=2.5652, REC=0.5951
tensor([[ 0.9661,  1.0288,  1.1260,  ...,  8.3486,  8.4085,  9.0176],
        [ 0.9916,  1.0300,  1.1917,  ...,  9.1652,  9.0829,  9.0950],
        [ 0.8940,  1.0320,  1.0143,  ...,  9.2618,  9.1654,  9.0550],
        ...,
        [ 0.8959,  1.0314,  1.0125,  ...,  8.7459,  8.5852,  8.4536],
        [ 0.9304,  1.0321,  1.0353,  ...,  5.3457,  5.4967,  5.9842],
        [ 0.8912,  1.0337,  1.0167,  ..., 10.0231, 10.0118,  9.9618]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 205/250 [00:08<00:01, 28.09it/s]

epoch 200: ARI=-0.0056, CCR=0.5000, CLU=2.5650, REC=0.5868
tensor([[ 0.8499,  1.0606,  1.0244,  ...,  9.2240,  9.3878,  9.4717],
        [ 1.0445,  1.0965,  1.2705,  ...,  8.9307,  8.9004,  8.9295],
        [ 0.8408,  1.0638,  1.0245,  ..., 10.4667, 10.4790, 10.4517],
        ...,
        [ 0.8443,  1.0622,  1.0239,  ...,  9.8716,  9.8489,  9.8191],
        [ 0.8651,  1.0541,  1.0222,  ...,  7.2804,  7.3701,  7.4604],
        [ 0.8389,  1.0648,  1.0249,  ..., 10.8084, 10.8545, 10.8323]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:10<00:00, 24.65it/s]
R[write to console]:                    __           __ 
   ____ ___  _____/ /_  _______/ /_
  / __ `__ \/ ___/ / / / / ___/ __/
 / / / / / / /__/ / /_/ (__  ) /_  
/_/ /_/ /_/\___/_/\__,_/____/\__/   version 6.1.2
Type 'citation("mclust")' for citing this R package in publications.



Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151507 ARI: 0.35481096
Figure saved to: figures_test/151507.png

==================== Processing Sample: 151508 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 105/250 [00:03<00:05, 27.23it/s]

epoch 100: ARI=0.0021, CCR=0.5007, CLU=2.5652, REC=0.5597
tensor([[ 1.1818,  1.1677,  1.2342,  ...,  9.7370,  9.6811,  9.5903],
        [ 0.9948,  1.0283,  1.0559,  ..., 10.1573,  9.9982,  9.6797],
        [ 0.9943,  1.0282,  1.0559,  ..., 10.1946, 10.0644,  9.7044],
        ...,
        [ 1.1762,  1.1633,  1.2250,  ...,  8.9940,  8.9466,  8.8488],
        [ 0.9945,  1.0276,  1.0550,  ..., 10.0135,  9.8911,  9.5279],
        [ 0.9944,  1.0284,  1.0560,  ..., 10.4785, 10.3303,  9.9581]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:07<00:01, 27.38it/s]

epoch 200: ARI=-0.0023, CCR=0.5004, CLU=2.5650, REC=0.5515
tensor([[ 1.2476,  1.2381,  1.2498,  ..., 10.3624, 10.3727, 10.2211],
        [ 0.9445,  1.0663,  1.0649,  ...,  9.7805,  9.7515,  9.3715],
        [ 0.9445,  1.0662,  1.0648,  ...,  9.7741,  9.7433,  9.3591],
        ...,
        [ 1.2395,  1.2302,  1.2416,  ...,  9.6173,  9.6198,  9.4880],
        [ 0.9445,  1.0663,  1.0649,  ...,  9.7779,  9.7504,  9.3678],
        [ 0.9443,  1.0665,  1.0652,  ...,  9.8783,  9.8529,  9.4643]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:09<00:00, 27.36it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151508 ARI: 0.27147164
Figure saved to: figures_test/151508.png

==================== Processing Sample: 151509 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 105/250 [00:04<00:05, 25.48it/s]

epoch 100: ARI=0.0122, CCR=0.4824, CLU=2.5652, REC=0.5784
tensor([[ 1.2562,  1.1356,  1.2699,  ...,  1.8091, 10.0307, 10.1616],
        [ 1.0963,  1.1244,  0.9921,  ...,  1.2351,  9.0109,  9.0619],
        [ 1.2500,  1.1306,  1.2610,  ...,  1.7879,  9.4132,  9.4577],
        ...,
        [ 1.0967,  1.1252,  0.9921,  ...,  1.2384,  9.3530,  9.3562],
        [ 1.2489,  1.1303,  1.2604,  ...,  1.7840,  9.3416,  9.4068],
        [ 1.0965,  1.1250,  0.9929,  ...,  1.2362,  9.1618,  9.1893]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:07<00:01, 25.55it/s]

epoch 200: ARI=0.0014, CCR=0.4272, CLU=2.5650, REC=0.5702
tensor([[ 1.2493,  1.1640,  1.3497,  ...,  1.7768,  9.1169,  9.1366],
        [ 1.1038,  1.1962,  1.0273,  ...,  1.2471, 10.8579, 10.8468],
        [ 1.2458,  1.1617,  1.3446,  ...,  1.7643,  8.8519,  8.8637],
        ...,
        [ 1.1038,  1.1962,  1.0273,  ...,  1.2471, 10.8620, 10.8477],
        [ 1.2465,  1.1622,  1.3456,  ...,  1.7669,  8.8974,  8.9047],
        [ 1.1011,  1.1907,  1.0266,  ...,  1.2403, 10.1721, 10.1710]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:09<00:00, 25.87it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151509 ARI: 0.39703533
Figure saved to: figures_test/151509.png

==================== Processing Sample: 151510 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 105/250 [00:03<00:05, 26.58it/s]

epoch 100: ARI=0.0020, CCR=0.5006, CLU=2.5652, REC=0.5751
tensor([[ 1.3125,  1.3054,  1.0707,  ...,  9.8949,  9.9052,  9.9203],
        [ 1.0621,  0.9552,  1.2395,  ...,  9.8116,  9.6284,  9.5905],
        [ 1.0644,  0.9629,  1.2233,  ...,  9.2837,  9.2610,  9.2953],
        ...,
        [ 1.0648,  0.9619,  1.2250,  ...,  9.3834,  9.3699,  9.3986],
        [ 1.3108,  1.3034,  1.0699,  ...,  9.7461,  9.7790,  9.7873],
        [ 1.0660,  0.9519,  1.2688,  ..., 11.4434, 11.6991, 11.4274]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:07<00:01, 26.44it/s]

epoch 200: ARI=0.0009, CCR=0.4698, CLU=2.5650, REC=0.5670
tensor([[ 1.2977,  1.3579,  1.0998,  ...,  9.7411,  9.6620,  9.6675],
        [ 1.1608,  1.1820,  1.0741,  ...,  4.4274,  4.2349,  4.3896],
        [ 1.0810,  1.0112,  1.2237,  ...,  9.5389,  9.5215,  9.5191],
        ...,
        [ 1.0818,  1.0113,  1.2262,  ...,  9.7497,  9.7413,  9.7338],
        [ 1.3006,  1.3614,  1.1007,  ...,  9.9288,  9.8538,  9.8560],
        [ 1.0849,  1.0112,  1.2365,  ..., 10.7675, 10.7693, 10.7626]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:09<00:00, 26.77it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151510 ARI: 0.57068687
Figure saved to: figures_test/151510.png

==================== Processing Sample: 151669 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 104/250 [00:03<00:04, 31.11it/s]

epoch 100: ARI=1.0000, CCR=0.5004, CLU=2.1976, REC=0.6760
tensor([[1.0700, 1.1026, 1.0934,  ..., 1.0610, 9.2287, 9.4162],
        [1.0692, 1.1022, 1.0929,  ..., 1.0607, 8.9844, 9.1973],
        [1.1553, 1.2562, 1.0371,  ..., 1.0342, 9.6697, 9.5548],
        ...,
        [1.0691, 1.1019, 1.0921,  ..., 1.0603, 8.8298, 9.0546],
        [1.0708, 1.1034, 1.0942,  ..., 1.0609, 9.3566, 9.5423],
        [1.1562, 1.2577, 1.0378,  ..., 1.0343, 9.7867, 9.6736]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 31.76it/s]

epoch 200: ARI=1.0000, CCR=0.5002, CLU=2.1973, REC=0.6685
tensor([[ 1.1085,  1.1319,  1.1481,  ...,  1.0699,  9.1921,  9.1287],
        [ 1.1081,  1.1314,  1.1475,  ...,  1.0697,  9.1192,  9.0543],
        [ 1.2501,  1.2465,  1.1163,  ...,  1.0062, 10.7044, 10.7641],
        ...,
        [ 1.1077,  1.1309,  1.1469,  ...,  1.0694,  9.0487,  8.9852],
        [ 1.1091,  1.1327,  1.1490,  ...,  1.0703,  9.3144,  9.2495],
        [ 1.2528,  1.2492,  1.1175,  ...,  1.0062, 10.9491, 11.0259]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|█████████▉| 249/250 [00:07<00:00, 31.30it/s]


fitting ...
  |======================================================================| 100%
Sample 151669 ARI: 0.62539878
Figure saved to: figures_test/151669.png

==================== Processing Sample: 151670 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 104/250 [00:03<00:04, 32.48it/s]

epoch 100: ARI=1.0000, CCR=0.5003, CLU=2.1977, REC=0.6674
tensor([[1.0287, 1.1416, 1.1147,  ..., 9.8952, 9.7694, 9.8594],
        [1.0283, 1.1406, 1.1139,  ..., 9.7743, 9.6306, 9.7279],
        [1.1925, 1.1398, 1.0165,  ..., 9.2990, 9.2536, 9.0743],
        ...,
        [1.0281, 1.1404, 1.1137,  ..., 9.7114, 9.5665, 9.6597],
        [1.0286, 1.1415, 1.1145,  ..., 9.9072, 9.7796, 9.8726],
        [1.1934, 1.1405, 1.0176,  ..., 9.5566, 9.4837, 9.3540]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 31.91it/s]

epoch 200: ARI=1.0000, CCR=0.5005, CLU=2.1973, REC=0.6603
tensor([[ 1.0627,  1.1829,  1.2017,  ...,  9.8605,  9.8450,  9.8421],
        [ 1.0631,  1.1842,  1.2032,  ..., 10.0129, 10.0040, 10.0061],
        [ 1.2957,  1.0946,  1.0440,  ...,  9.5887,  9.6112,  9.5620],
        ...,
        [ 1.0629,  1.1834,  1.2023,  ...,  9.9242,  9.9114,  9.9108],
        [ 1.0629,  1.1834,  1.2023,  ...,  9.9243,  9.9106,  9.9104],
        [ 1.2955,  1.0945,  1.0439,  ...,  9.5805,  9.6003,  9.5472]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|█████████▉| 249/250 [00:07<00:00, 32.55it/s]


fitting ...
  |======================================================================| 100%
Sample 151670 ARI: 0.42535414
Figure saved to: figures_test/151670.png

==================== Processing Sample: 151671 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 105/250 [00:03<00:05, 28.78it/s]

epoch 100: ARI=1.0000, CCR=0.5007, CLU=2.1977, REC=0.6713
tensor([[ 0.9525,  1.0835,  0.9377,  ...,  1.0823,  1.1857, 10.1608],
        [ 0.9487,  1.0829,  0.9318,  ...,  1.0818,  1.1796, 10.2298],
        [ 1.1452,  1.1019,  0.9156,  ...,  1.1780,  0.8864,  9.6997],
        ...,
        [ 0.9462,  1.0837,  0.9292,  ...,  1.0830,  1.1840, 10.7903],
        [ 0.8695,  1.0047,  0.8881,  ...,  1.1892,  0.8257,  8.4514],
        [ 1.1511,  1.1034,  0.9160,  ...,  1.1750,  0.8920,  9.6398]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:07<00:01, 28.51it/s]

epoch 200: ARI=1.0000, CCR=0.5002, CLU=2.1973, REC=0.6624
tensor([[ 1.0555,  1.0944,  1.0127,  ...,  1.0893,  1.2239, 10.1577],
        [ 1.0510,  1.0914,  1.0092,  ...,  1.0894,  1.2186, 10.0313],
        [ 1.1797,  1.0896,  0.9475,  ...,  1.2206,  0.9744, 10.3457],
        ...,
        [ 1.0462,  1.0886,  1.0055,  ...,  1.0898,  1.2137,  9.9859],
        [ 0.8411,  0.9650,  0.7884,  ...,  1.2094,  0.9156, 10.0760],
        [ 1.1882,  1.0922,  0.9539,  ...,  1.2166,  0.9782, 10.0481]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|█████████▉| 249/250 [00:08<00:00, 28.93it/s]


fitting ...
  |======================================================================| 100%
Sample 151671 ARI: 0.56986248
Figure saved to: figures_test/151671.png

==================== Processing Sample: 151672 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 105/250 [00:03<00:05, 28.80it/s]

epoch 100: ARI=1.0000, CCR=0.5005, CLU=2.1977, REC=0.6678
tensor([[ 0.8900,  1.2293,  1.0537,  ...,  1.0016,  1.1627, 10.0759],
        [ 0.8889,  1.2284,  1.0378,  ...,  0.9909,  1.1556,  9.8716],
        [ 0.9047,  1.0676,  1.1738,  ...,  1.1144,  1.1143,  9.5578],
        ...,
        [ 0.8905,  1.2186,  1.0113,  ...,  0.9753,  1.1376,  8.8116],
        [ 0.8885,  1.2336,  1.0568,  ...,  1.0027,  1.1670, 10.5382],
        [ 0.9044,  1.0687,  1.1749,  ...,  1.1149,  1.1151,  9.6725]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 205/250 [00:07<00:01, 28.87it/s]

epoch 200: ARI=1.0000, CCR=0.5002, CLU=2.1973, REC=0.6574
tensor([[ 0.9955,  1.2255,  1.1513,  ...,  1.0297,  1.2123, 10.4887],
        [ 0.9820,  1.2271,  1.1236,  ...,  1.0098,  1.1920, 10.7111],
        [ 0.9350,  1.0791,  1.2422,  ...,  1.0885,  1.1427,  9.2812],
        ...,
        [ 0.9192,  1.2275,  0.9939,  ...,  0.9176,  1.0919, 11.0584],
        [ 1.0050,  1.2198,  1.1680,  ...,  1.0433,  1.2223,  9.8877],
        [ 0.9344,  1.0798,  1.2448,  ...,  1.0894,  1.1441,  9.4882]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|█████████▉| 249/250 [00:08<00:00, 28.76it/s]


fitting ...
  |======================================================================| 100%
Sample 151672 ARI: 0.68481669
Figure saved to: figures_test/151672.png

==================== Processing Sample: 151673 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 41%|████      | 103/250 [00:03<00:04, 30.97it/s]

epoch 100: ARI=0.0153, CCR=0.4027, CLU=2.5652, REC=0.7323
tensor([[1.1617, 0.8187, 1.1509,  ..., 1.0508, 1.4484, 1.2019],
        [1.0881, 1.4170, 0.9733,  ..., 1.1000, 2.1611, 0.9447],
        [1.0672, 1.4618, 0.9844,  ..., 1.0976, 2.1948, 0.9438],
        ...,
        [1.0827, 1.4510, 0.9775,  ..., 1.1027, 2.2308, 0.9437],
        [1.0707, 1.4653, 0.9827,  ..., 1.0994, 2.2167, 0.9430],
        [1.1507, 0.8745, 1.0906,  ..., 1.0400, 1.4267, 1.1461]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 81%|████████  | 203/250 [00:06<00:01, 30.14it/s]

epoch 200: ARI=0.0028, CCR=0.3815, CLU=2.5650, REC=0.7227
tensor([[1.1598, 0.8205, 1.2124,  ..., 1.1438, 1.4908, 1.2722],
        [1.1185, 1.2044, 1.0111,  ..., 1.1084, 1.7132, 1.0043],
        [1.0649, 1.6242, 1.0422,  ..., 1.1707, 2.4702, 0.9964],
        ...,
        [1.0945, 1.4058, 1.0268,  ..., 1.1421, 2.0857, 1.0004],
        [1.0681, 1.6011, 1.0406,  ..., 1.1678, 2.4287, 0.9968],
        [1.1734, 0.7884, 1.2010,  ..., 1.1390, 1.4397, 1.2681]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151673 ARI: 0.44046062
Figure saved to: figures_test/151673.png

==================== Processing Sample: 151674 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 41%|████      | 103/250 [00:03<00:04, 30.70it/s]

epoch 100: ARI=0.0027, CCR=0.4281, CLU=2.5652, REC=0.7910
tensor([[1.0368, 1.1116, 1.1288,  ..., 1.0540, 0.9834, 1.6868],
        [1.3565, 0.9569, 1.0751,  ..., 1.1875, 1.2568, 2.2889],
        [1.3394, 0.9596, 1.0756,  ..., 1.1794, 1.2449, 2.2385],
        ...,
        [1.3646, 0.9559, 1.0783,  ..., 1.1916, 1.2627, 2.3404],
        [1.3560, 0.9573, 1.0762,  ..., 1.1874, 1.2575, 2.3044],
        [1.3765, 0.9560, 1.0730,  ..., 1.1982, 1.2715, 2.3531]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 81%|████████  | 203/250 [00:06<00:01, 30.92it/s]

epoch 200: ARI=0.0020, CCR=0.4075, CLU=2.5650, REC=0.7819
tensor([[1.0248, 1.1761, 1.1864,  ..., 1.0558, 0.9946, 1.6797],
        [1.3442, 1.0212, 1.1393,  ..., 1.2368, 1.3022, 2.3363],
        [1.3494, 1.0215, 1.1418,  ..., 1.2412, 1.3077, 2.3759],
        ...,
        [1.3593, 1.0220, 1.1451,  ..., 1.2472, 1.3158, 2.4181],
        [1.3589, 1.0220, 1.1451,  ..., 1.2472, 1.3156, 2.4192],
        [1.3563, 1.0219, 1.1433,  ..., 1.2439, 1.3120, 2.3868]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:07<00:00, 31.54it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151674 ARI: 0.42567113
Figure saved to: figures_test/151674.png

==================== Processing Sample: 151675 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 104/250 [00:03<00:04, 31.93it/s]

epoch 100: ARI=0.0126, CCR=0.4115, CLU=2.5652, REC=0.6930
tensor([[1.0904, 0.9424, 0.9512,  ..., 0.9972, 1.0579, 1.2056],
        [1.1160, 0.9169, 0.9174,  ..., 0.9832, 1.0731, 1.2677],
        [1.0937, 1.1147, 1.7397,  ..., 1.3754, 1.1075, 2.3329],
        ...,
        [1.0973, 1.1160, 1.7591,  ..., 1.3870, 1.1126, 2.3733],
        [1.0712, 0.9553, 0.9639,  ..., 0.9994, 1.0443, 1.1610],
        [1.1058, 1.1075, 1.7734,  ..., 1.3971, 1.1177, 2.3446]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 32.42it/s]

epoch 200: ARI=0.0049, CCR=0.4024, CLU=2.5650, REC=0.6707
tensor([[1.1697, 0.9738, 0.9375,  ..., 1.0480, 1.1598, 1.2109],
        [1.2167, 0.9696, 0.9249,  ..., 1.0630, 1.2080, 1.2755],
        [1.0317, 1.0417, 1.4268,  ..., 1.2480, 1.0574, 1.9554],
        ...,
        [1.0315, 1.0417, 1.4268,  ..., 1.2478, 1.0572, 1.9551],
        [1.0396, 1.0335, 1.3765,  ..., 1.2340, 1.0619, 1.8488],
        [1.0334, 1.0406, 1.4224,  ..., 1.2481, 1.0587, 1.9479]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:07<00:00, 32.39it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151675 ARI: 0.28946675
Figure saved to: figures_test/151675.png

==================== Processing Sample: 151676 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 42%|████▏     | 104/250 [00:03<00:04, 32.37it/s]

epoch 100: ARI=-0.0162, CCR=0.4276, CLU=2.5652, REC=0.7076
tensor([[1.1751, 1.1318, 0.9175,  ..., 1.0334, 1.1230, 1.3928],
        [1.1677, 1.1276, 0.9203,  ..., 1.0336, 1.1179, 1.3749],
        [1.0787, 1.0644, 1.3704,  ..., 0.9597, 1.0843, 1.9793],
        ...,
        [1.0795, 1.0647, 1.3732,  ..., 0.9595, 1.0852, 1.9874],
        [1.0811, 1.0644, 1.3744,  ..., 0.9583, 1.0866, 1.9912],
        [1.1594, 1.1226, 0.9224,  ..., 1.0330, 1.1130, 1.3578]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 32.64it/s]

epoch 200: ARI=0.0034, CCR=0.4218, CLU=2.5650, REC=0.6998
tensor([[1.1896, 1.2053, 0.9183,  ..., 1.0913, 1.1620, 1.4138],
        [1.1802, 1.1953, 0.9218,  ..., 1.0871, 1.1542, 1.3942],
        [1.0984, 1.0831, 1.4011,  ..., 1.0206, 1.1567, 1.8967],
        ...,
        [1.0987, 1.0834, 1.4022,  ..., 1.0207, 1.1572, 1.8994],
        [1.1020, 1.0864, 1.4158,  ..., 1.0216, 1.1629, 1.9318],
        [1.1722, 1.1869, 0.9248,  ..., 1.0834, 1.1476, 1.3778]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:07<00:00, 33.00it/s]


Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151676 ARI: 0.46436555
Figure saved to: figures_test/151676.png

==================== Final Results ====================
ARI per slice: [0.35481, 0.27147, 0.39704, 0.57069, 0.6254, 0.42535, 0.56986, 0.68482, 0.44046, 0.42567, 0.28947, 0.46437]
Mean ARI: 0.4600
Median ARI: 0.4331
