In [1]:
import scanpy as sc 
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.metrics import adjusted_rand_score
from sklearn.decomposition import PCA

import scipy.sparse as sp 
import warnings

warnings.filterwarnings("ignore")

import os
import ctypes
import sys

# 1. 先设置 R_HOME
os.environ["R_HOME"] = "/home/pxy/miniconda3/envs/r40/lib/R"

# 2. 【核心黑科技】手动加载 R 的动态库
# 这步操作等同于在终端里设置 LD_LIBRARY_PATH，专门解决 VS Code 找不到库的问题
try:
    # 这是 R 的核心库路径
    libR_path = "/home/pxy/miniconda3/envs/r40/lib/R/lib/libR.so"
    # 强制加载进内存
    ctypes.CDLL(libR_path, mode=ctypes.RTLD_GLOBAL)
    print("✅ 成功强制加载 libR.so")
except OSError as e:
    print(f"❌ 加载失败: {e}")

# 3. 然后再导入其他包
sys.path.append("..") 

import spCLUE
import rpy2.robjects as robjects
print("R 环境路径:", robjects.r['R.home']()[0])

spCLUE.fix_seed(0)

# 定义DLPFC数据集的12个切片ID
slice_ids = [
    "151507", "151508", "151509", "151510",
    "151669", "151670", "151671", "151672",
    "151673", "151674", "151675", "151676"
]

# 用于存储每个切片的ARI结果
ari_results = []

# 数据路径（请根据实际情况确认路径是否正确）
data_dir = '/home/pxy/home/pxy/data/DLPFC/st/'

# 【新增】创建保存图片的文件夹
figures_dir = "figures_test"
if not os.path.exists(figures_dir):
    os.makedirs(figures_dir)
    print(f"Created directory: {figures_dir}")

print(f"Start processing {len(slice_ids)} slices...")

for sample_name in slice_ids:
    print(f"\n{'='*20} Processing Sample: {sample_name} {'='*20}")
    
    # 1. 设置簇的数量 (根据DLPFC数据集的已知Ground Truth)
    # 151669-151672 通常只有5层，其他切片为7层
    if sample_name in ["151669", "151670", "151671", "151672"]:
        n_clusters = 5
    else:
        n_clusters = 7
    
    try:
        # 2. 加载数据
        # 使用 read_visium 加载数据，路径拼接逻辑参考原文件
        adata = sc.read_visium(data_dir + sample_name)
        adata.var_names_make_unique()
        
        # 加载元数据 (Ground Truth)
        meta = pd.read_csv(data_dir + sample_name + "/metadata.tsv", sep="\t")
        meta = meta.set_index("barcode")
        adata.obs["Region"] = meta.loc[adata.obs_names, "layer_guess_reordered"]
        
        # 3. 数据预处理与构图
        # 原文件 Cell 6 的逻辑
        # adata = spCLUE.preprocess(adata)
        # adata.obsm["X_pca"] = PCA(n_components=200, random_state=0).fit_transform(adata.X)
        
        # g_spatial = spCLUE.prepare_graph(adata, "spatial", n_neighbors=6)
        # g_expr = spCLUE.prepare_graph(adata, "expr", metric="euclidean", n_neighbors=8)
        from spCLUE.preprocess import (
            prepare_euclidean_graph, 
            prepare_cosine_graph, 
            prepare_fused_graph
        )

        # 1. 数据预处理
        adata = spCLUE.preprocess(adata, hvgNumber=3000)

        # 2. 构建三个视图的图
        adj_s, g_spatial = prepare_euclidean_graph(adata,)
        adj_f, g_feature = prepare_cosine_graph(adata, k=14)
        g_combined = prepare_fused_graph(adj_s, adj_f)

        # 3. 准备图字典
        graph_dict = {
            "spatial": g_spatial,
            "feature": g_feature,
            "combined": g_combined,
        }
        use_zinb = True
        
        # 4. 模型初始化与训练
        # 原文件 Cell 8 的逻辑
        # 注意：这里将 n_clusters 参数改为动态变量，与当前切片保持一致
        # spCLUE_model = spCLUE.spCLUE(adata.obsm["X_pca"], graph_dict, n_clusters,
                                    # )
        # _, adata.obsm["spCLUE"], att_beta = spCLUE_model.train()
        import scipy.sparse as sp

        input_x = adata.X
        if sp.issparse(input_x):
            input_x = input_x.toarray() # 将稀疏矩阵转为普通的 numpy array
        if "raw_count" in graph_dict and sp.issparse(graph_dict["raw_count"]):
            graph_dict["raw_count"] = graph_dict["raw_count"].toarray()
        spCLUE_model = spCLUE.spCLUE(
            input_data=input_x,
            graph_dict=graph_dict,
            n_clusters=n_clusters,
            lambda_ccr=5.0,  # CCR损失权重
            use_zinb=True,  # 是否使用ZINB解码器
            # kappa=0.1,
            beta=1.0,
            gamma=1.0,
        )
        _, adata.obsm["spCLUE"], attention_weights = spCLUE_model.train()
        
        # 5. 聚类
        # 原文件 Cell 10 的逻辑
        refinement = True
        cluster_method = "mclust"
        spCLUE.clustering(
            adata,
            n_clusters,
            key="spCLUE",
            refinement=refinement,
            cluster_methods=cluster_method,
        )
        
        # 6. 计算 ARI
        # 原文件 Cell 12 的逻辑
        # 过滤掉 Ground Truth 为 NA 的区域
        adata_valid = adata[adata.obs.Region.notna()]
        ARI = adjusted_rand_score(adata_valid.obs["Region"], adata_valid.obs["mclust_refined"])
        
        print(f"Sample {sample_name} ARI: {ARI:.8f}")
        ari_results.append(ARI)

        # 绘图：show=False 防止直接显示，便于后续保存
        adata.obs["spCLUE"] = adata.obs["mclust_refined"]
        sc.pl.spatial(
            adata, 
            color=["Region", "spCLUE"], 
            title=["Manual Annotation", f"spCLUE (ARI={round(ARI, 2)})"],
            show=False 
        )
        
        # 保存路径
        save_path = os.path.join(figures_dir, f"{sample_name}.png")
        
        # 保存图片 (bbox_inches='tight' 去除多余白边, dpi=300 保证清晰度)
        plt.savefig(save_path, bbox_inches='tight', dpi=300)
        
        # 关闭当前图形，释放内存 (在循环中非常重要，否则内存会爆)
        plt.close()
        
        print(f"Figure saved to: {save_path}")
        
    except Exception as e:
        print(f"Error processing sample {sample_name}: {e}")

# 7. 输出最终统计结果
print(f"\n{'='*20} Final Results {'='*20}")
if ari_results:
    mean_ari = np.mean(ari_results)
    median_ari = np.median(ari_results)
    print(f"ARI per slice: {[round(x, 5) for x in ari_results]}")
    print(f"Mean ARI: {mean_ari:.4f}")
    print(f"Median ARI: {median_ari:.4f}")
else:
    print("No ARI results collected.")

✅ 成功强制加载 libR.so
R 环境路径: /home/pxy/miniconda3/envs/r40/lib/R
Start processing 12 slices...

==================== Processing Sample: 151507 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 22%|██▏       | 55/250 [00:03<00:07, 26.86it/s]

epoch 50: ARI=0.0736, CCR=0.5000, CLU=2.5650, REC=0.6112
tensor([[ 0.8655,  0.8499,  1.1411,  ...,  6.9170,  6.7984,  6.9034],
        [ 0.8715,  0.8240,  1.1328,  ...,  9.6693,  8.4650,  9.2720],
        [ 0.7427,  0.8475,  1.1024,  ..., 11.2582, 11.4543,  6.4753],
        ...,
        [ 0.7578,  0.8665,  1.0862,  ...,  9.6990,  9.3726,  6.0062],
        [ 0.8373,  0.7834,  1.0986,  ..., 10.7295,  9.6384,  9.1231],
        [ 0.7388,  0.8419,  1.1019,  ..., 11.4920, 11.9907,  6.4921]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 41%|████      | 103/250 [00:04<00:05, 27.07it/s]

epoch 100: ARI=-0.0187, CCR=0.4979, CLU=2.5649, REC=0.5954
tensor([[ 0.8715,  0.9868,  1.0327,  ...,  5.3568,  6.2727,  5.5100],
        [ 0.9665,  0.9498,  1.2050,  ..., 11.2701, 11.1290, 11.1495],
        [ 0.8415,  0.9937,  1.0223,  ...,  7.8377,  7.4992,  7.7439],
        ...,
        [ 0.8466,  0.9949,  1.0219,  ...,  7.3419,  6.9051,  7.2216],
        [ 0.9646,  0.9578,  1.1974,  ..., 10.4626, 11.4507, 10.6208],
        [ 0.8382,  0.9925,  1.0224,  ...,  8.1389,  7.9550,  8.0880]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 62%|██████▏   | 154/250 [00:06<00:03, 27.58it/s]

epoch 150: ARI=0.1445, CCR=0.4373, CLU=2.5145, REC=0.5888
tensor([[ 0.8391,  1.0212,  1.0276,  ...,  9.5104,  9.6361,  9.5303],
        [ 1.0242,  1.0521,  1.2623,  ..., 10.2654, 10.2677, 10.2444],
        [ 0.8427,  1.0210,  1.0269,  ...,  9.0068,  8.9330,  8.9647],
        ...,
        [ 0.8430,  1.0210,  1.0269,  ...,  8.9811,  8.9038,  8.9837],
        [ 1.0071,  1.0404,  1.1963,  ...,  6.9340,  7.2324,  7.1999],
        [ 0.8417,  1.0211,  1.0271,  ...,  9.1424,  9.0999,  9.1006]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 205/250 [00:08<00:01, 27.20it/s]

epoch 200: ARI=0.2754, CCR=0.4149, CLU=1.9742, REC=0.5862
tensor([[ 0.8290,  1.0517,  1.0177,  ...,  9.6898,  9.6730,  9.6223],
        [ 1.0437,  1.0853,  1.2882,  ..., 10.2116, 10.2285, 10.2071],
        [ 0.8316,  1.0508,  1.0174,  ...,  9.3318,  9.2498,  9.2403],
        ...,
        [ 0.8335,  1.0502,  1.0172,  ...,  9.0912,  8.9986,  9.0150],
        [ 1.0452,  1.0886,  1.2995,  ..., 11.1089, 11.2649, 11.1636],
        [ 0.8302,  1.0513,  1.0175,  ...,  9.5208,  9.4519,  9.4281]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:10<00:00, 24.19it/s]
R[write to console]:                    __           __ 
   ____ ___  _____/ /_  _______/ /_
  / __ `__ \/ ___/ / / / / ___/ __/
 / / / / / / /__/ / /_/ (__  ) /_  
/_/ /_/ /_/\___/_/\__,_/____/\__/   version 6.1.2
Type 'citation("mclust")' for citing this R package in publications.



epoch 250: ARI=0.1948, CCR=0.4101, CLU=1.7543, REC=0.5851
tensor([[ 0.8390,  1.0685,  1.0145,  ...,  9.2373,  9.2453,  9.3103],
        [ 1.0570,  1.1046,  1.3142,  ..., 10.8149, 10.8275, 10.7952],
        [ 0.8398,  1.0681,  1.0144,  ...,  9.1192,  9.1160,  9.1882],
        ...,
        [ 0.8418,  1.0672,  1.0143,  ...,  8.8730,  8.8601,  8.9444],
        [ 1.0594,  1.1092,  1.3290,  ..., 11.9464, 12.1046, 11.9845],
        [ 0.8386,  1.0686,  1.0145,  ...,  9.2854,  9.2925,  9.3566]],
       device='cuda:0', grad_fn=<ClampBackward1>)
Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151507 ARI: 0.39270518
Figure saved to: figures_test/151507.png

==================== Processing Sample: 151508 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-

 22%|██▏       | 54/250 [00:01<00:07, 26.97it/s]

epoch 50: ARI=0.0000, CCR=0.5001, CLU=2.5650, REC=0.5799
tensor([[ 0.9363,  0.9978,  1.0321,  ...,  1.5099,  1.3406,  1.4736],
        [ 0.7239,  0.8254,  1.0718,  ...,  8.3211,  8.1349,  7.5992],
        [ 0.7232,  0.8269,  1.0722,  ...,  8.3479,  8.1545,  7.5761],
        ...,
        [ 1.1467,  0.9829,  1.2499,  ..., 14.5727, 14.2934, 11.1145],
        [ 0.7265,  0.8289,  1.0723,  ...,  8.1829,  7.9953,  7.4429],
        [ 0.7251,  0.8274,  1.0713,  ...,  8.2138,  8.0080,  7.5164]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 105/250 [00:03<00:05, 26.92it/s]

epoch 100: ARI=0.0032, CCR=0.5000, CLU=2.5649, REC=0.5601
tensor([[ 1.1998,  1.1047,  1.2390,  ..., 10.1668, 10.3661,  9.9740],
        [ 0.8610,  0.9643,  1.0438,  ...,  9.7937,  9.7973,  9.4421],
        [ 0.8613,  0.9645,  1.0437,  ...,  9.7311,  9.7296,  9.3713],
        ...,
        [ 1.1954,  1.1045,  1.2369,  ...,  9.8593,  9.9092,  9.5929],
        [ 0.8618,  0.9647,  1.0435,  ...,  9.6616,  9.6576,  9.3057],
        [ 0.8614,  0.9645,  1.0436,  ...,  9.7276,  9.7287,  9.3788]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 61%|██████    | 153/250 [00:05<00:03, 26.57it/s]

epoch 150: ARI=0.0958, CCR=0.4985, CLU=2.5649, REC=0.5555
tensor([[ 1.2058,  1.1790,  1.2233,  ...,  8.2730,  8.1427,  8.1040],
        [ 0.9062,  1.0254,  1.0554,  ..., 12.6209, 12.7762, 12.1028],
        [ 0.9065,  1.0253,  1.0552,  ..., 12.4992, 12.6431, 11.9769],
        ...,
        [ 1.2011,  1.1752,  1.2186,  ...,  7.9307,  7.7704,  7.7575],
        [ 0.9067,  1.0253,  1.0551,  ..., 12.4449, 12.5857, 11.9256],
        [ 0.9063,  1.0253,  1.0553,  ..., 12.5661, 12.7187, 12.0500]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 80%|███████▉  | 199/250 [00:07<00:01, 26.89it/s]


epoch 200: ARI=0.4972, CCR=0.4300, CLU=2.5232, REC=0.5512
tensor([[ 1.2483,  1.2482,  1.2532,  ..., 10.6941, 10.5158, 10.3553],
        [ 0.9371,  1.0347,  1.0581,  ...,  9.7781,  9.7763,  9.4657],
        [ 0.9366,  1.0349,  1.0585,  ...,  9.9569,  9.9638,  9.6383],
        ...,
        [ 1.2382,  1.2381,  1.2433,  ...,  9.8155,  9.5834,  9.4926],
        [ 0.9358,  1.0353,  1.0592,  ..., 10.2181, 10.2385,  9.8897],
        [ 0.9387,  1.0339,  1.0566,  ...,  9.2226,  9.1932,  8.9307]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151508 ARI: 0.27056727
Figure saved to: figures_test/151508.png

==================== Processing Sample: 151509 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) ======================

 22%|██▏       | 54/250 [00:02<00:07, 25.62it/s]

epoch 50: ARI=0.7555, CCR=0.4992, CLU=2.5650, REC=0.5927
tensor([[ 1.1459,  0.9271,  1.3331,  ...,  1.7525,  9.2933,  8.3143],
        [ 1.0776,  0.9758,  0.9735,  ...,  1.2827, 10.7252,  9.2168],
        [ 1.1454,  0.9256,  1.3347,  ...,  1.7507,  9.3015,  8.2366],
        ...,
        [ 1.0843,  0.9729,  0.9727,  ...,  1.2927, 11.5826,  9.9659],
        [ 1.1434,  0.9250,  1.3340,  ...,  1.7496,  9.1891,  8.1028],
        [ 1.0783,  0.9777,  0.9739,  ...,  1.2894, 11.0660,  9.5611]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 105/250 [00:04<00:05, 25.54it/s]

epoch 100: ARI=0.1943, CCR=0.4743, CLU=2.5638, REC=0.5777
tensor([[ 1.2111,  1.0698,  1.3377,  ...,  1.7514,  9.1946,  9.4004],
        [ 1.0863,  1.0942,  0.9705,  ...,  1.2504, 10.2782, 10.1207],
        [ 1.2115,  1.0699,  1.3384,  ...,  1.7530,  9.1963,  9.4292],
        ...,
        [ 1.0872,  1.0945,  0.9700,  ...,  1.2523, 10.4584, 10.2950],
        [ 1.2091,  1.0692,  1.3347,  ...,  1.7446,  9.0100,  9.2497],
        [ 1.0851,  1.0932,  0.9706,  ...,  1.2481, 10.0153,  9.8783]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 61%|██████    | 153/250 [00:06<00:03, 24.82it/s]

epoch 150: ARI=0.4908, CCR=0.4067, CLU=2.0213, REC=0.5721
tensor([[ 1.2424,  1.1453,  1.3609,  ...,  1.7665,  9.1525,  9.1572],
        [ 1.0968,  1.1587,  1.0032,  ...,  1.2462, 10.5393, 10.4794],
        [ 1.2274,  1.1369,  1.3381,  ...,  1.7126,  8.0724,  8.1327],
        ...,
        [ 1.0975,  1.1600,  1.0032,  ...,  1.2482, 10.7409, 10.6695],
        [ 1.2421,  1.1452,  1.3605,  ...,  1.7656,  9.1126,  9.1379],
        [ 1.0963,  1.1579,  1.0031,  ...,  1.2450, 10.4257, 10.3703]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 80%|███████▉  | 199/250 [00:07<00:02, 25.11it/s]


epoch 200: ARI=0.3160, CCR=0.3976, CLU=1.7682, REC=0.5696
tensor([[ 1.2603,  1.1771,  1.3781,  ...,  1.7778,  9.2272,  9.2652],
        [ 1.0995,  1.1826,  1.0213,  ...,  1.2377, 10.1912, 10.1649],
        [ 1.2449,  1.1671,  1.3549,  ...,  1.7248,  8.1772,  8.2572],
        ...,
        [ 1.1002,  1.1839,  1.0214,  ...,  1.2394, 10.3510, 10.3162],
        [ 1.2646,  1.1799,  1.3847,  ...,  1.7931,  9.5322,  9.5590],
        [ 1.0988,  1.1814,  1.0212,  ...,  1.2361, 10.0323, 10.0130]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151509 ARI: 0.39328216
Figure saved to: figures_test/151509.png

==================== Processing Sample: 151510 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) ======================

 22%|██▏       | 54/250 [00:01<00:06, 29.55it/s]

epoch 50: ARI=0.0000, CCR=0.4996, CLU=2.5650, REC=0.5912
tensor([[ 1.1594,  0.9749,  1.2159,  ...,  9.7601, 10.4302,  9.0446],
        [ 1.0315,  0.8831,  1.1753,  ...,  7.8200,  7.1996,  6.2445],
        [ 1.0408,  0.8724,  1.2068,  ..., 10.2244,  9.5815,  8.0988],
        ...,
        [ 1.0394,  0.8719,  1.2041,  ..., 10.2504,  9.4984,  8.0814],
        [ 1.1410,  0.9787,  1.2008,  ...,  9.6693, 10.4449,  9.0163],
        [ 1.0462,  0.8684,  1.1998,  ...,  9.5644,  9.2029,  7.3704]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 105/250 [00:03<00:04, 29.50it/s]

epoch 100: ARI=0.2970, CCR=0.4793, CLU=2.5645, REC=0.5749
tensor([[ 1.2534,  1.1943,  1.1136,  ..., 10.3934, 10.4129, 10.4510],
        [ 1.0642,  0.9185,  1.2370,  ..., 11.1215, 11.5756, 10.9402],
        [ 1.0579,  0.9269,  1.2218,  ...,  9.5406,  9.4597,  9.3641],
        ...,
        [ 1.0573,  0.9277,  1.2199,  ...,  9.3827,  9.2472,  9.2069],
        [ 1.2555,  1.1968,  1.1143,  ..., 10.6632, 10.6539, 10.6609],
        [ 1.0672,  0.9361,  1.2066,  ...,  8.9785,  9.7295,  9.0493]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 61%|██████    | 153/250 [00:05<00:03, 29.49it/s]

epoch 150: ARI=0.3253, CCR=0.4267, CLU=2.0350, REC=0.5690
tensor([[ 1.2745,  1.2931,  1.1084,  ...,  8.8667,  8.7912,  8.8212],
        [ 1.0718,  0.9727,  1.2226,  ...,  9.6854,  9.7029,  9.6410],
        [ 1.0707,  0.9735,  1.2191,  ...,  9.3583,  9.2989,  9.3146],
        ...,
        [ 1.0703,  0.9736,  1.2180,  ...,  9.2591,  9.1873,  9.2147],
        [ 1.2766,  1.2957,  1.1088,  ...,  8.9778,  8.8966,  8.9194],
        [ 1.0757,  0.9722,  1.2321,  ..., 10.6488, 10.8940, 10.5549]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 29.52it/s]

epoch 200: ARI=0.1844, CCR=0.4101, CLU=1.8559, REC=0.5671
tensor([[1.3008, 1.3496, 1.1127,  ..., 9.3279, 9.2269, 9.2430],
        [1.0757, 0.9985, 1.2106,  ..., 8.7308, 8.7083, 8.7757],
        [1.0767, 0.9985, 1.2136,  ..., 8.9477, 8.9136, 8.9929],
        ...,
        [1.0758, 0.9986, 1.2110,  ..., 8.7335, 8.6832, 8.7754],
        [1.2987, 1.3475, 1.1116,  ..., 9.1740, 9.0552, 9.0778],
        [1.0799, 0.9982, 1.2232,  ..., 9.7905, 9.8398, 9.8526]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:08<00:00, 29.63it/s]


epoch 250: ARI=0.1766, CCR=0.4070, CLU=1.7148, REC=0.5658
tensor([[1.3052, 1.3622, 1.1189,  ..., 8.9946, 8.8152, 8.8508],
        [1.0791, 1.0125, 1.2089,  ..., 9.2467, 9.2466, 9.2875],
        [1.0799, 1.0126, 1.2113,  ..., 9.4526, 9.4524, 9.4928],
        ...,
        [1.0790, 1.0125, 1.2087,  ..., 9.2142, 9.1986, 9.2511],
        [1.3026, 1.3592, 1.1178,  ..., 8.8372, 8.6492, 8.6920],
        [1.0815, 1.0128, 1.2157,  ..., 9.8643, 9.9026, 9.9137]],
       device='cuda:0', grad_fn=<ClampBackward1>)
Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151510 ARI: 0.36447631
Figure saved to: figures_test/151510.png

==================== Processing Sample: 151669 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =====================

 22%|██▏       | 56/250 [00:01<00:06, 30.35it/s]

epoch 50: ARI=1.0000, CCR=0.5001, CLU=2.1973, REC=0.6893
tensor([[ 1.0825,  1.1074,  0.8823,  ...,  0.9494, 11.0101, 10.5105],
        [ 1.0820,  1.1058,  0.8824,  ...,  0.9477, 10.5877, 10.1510],
        [ 1.0045,  1.0674,  0.8868,  ...,  0.9792,  9.7439,  9.4375],
        ...,
        [ 1.0802,  1.1060,  0.8838,  ...,  0.9472, 10.2968,  9.8363],
        [ 1.0813,  1.1052,  0.8844,  ...,  0.9464, 10.5419, 10.0995],
        [ 1.0015,  1.0695,  0.8874,  ...,  0.9808,  9.8711,  9.4984]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 104/250 [00:03<00:04, 30.15it/s]

epoch 100: ARI=-0.0018, CCR=0.5000, CLU=2.1972, REC=0.6759
tensor([[ 1.1016,  1.1228,  1.0273,  ...,  1.0459, 10.5262, 10.4484],
        [ 1.1001,  1.1213,  1.0269,  ...,  1.0445, 10.2157, 10.1283],
        [ 1.1128,  1.1397,  1.0182,  ...,  1.0072,  8.8741,  8.8634],
        ...,
        [ 1.0994,  1.1206,  1.0267,  ...,  1.0443, 10.0938,  9.9979],
        [ 1.1005,  1.1217,  1.0271,  ...,  1.0445, 10.2887, 10.2054],
        [ 1.1133,  1.1407,  1.0181,  ...,  1.0072,  8.9749,  8.9637]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 62%|██████▏   | 156/250 [00:05<00:03, 30.66it/s]

epoch 150: ARI=-0.0049, CCR=0.5000, CLU=2.1972, REC=0.6703
tensor([[ 1.1105,  1.1336,  1.1145,  ...,  1.0660, 10.2360, 10.2286],
        [ 1.1098,  1.1327,  1.1137,  ...,  1.0655, 10.0786, 10.0700],
        [ 1.1878,  1.1916,  1.0733,  ...,  1.0053,  9.2432,  9.2452],
        ...,
        [ 1.1093,  1.1321,  1.1132,  ...,  1.0652,  9.9920,  9.9810],
        [ 1.1102,  1.1331,  1.1141,  ...,  1.0657, 10.1575, 10.1505],
        [ 1.1904,  1.1942,  1.0741,  ...,  1.0053,  9.4995,  9.5085]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 81%|████████  | 203/250 [00:06<00:01, 30.20it/s]

epoch 200: ARI=0.0069, CCR=0.4996, CLU=2.1972, REC=0.6681
tensor([[ 1.1204,  1.1451,  1.1552,  ...,  1.0842, 10.2308, 10.2415],
        [ 1.1195,  1.1440,  1.1540,  ...,  1.0836, 10.0665, 10.0749],
        [ 1.2210,  1.2122,  1.0959,  ...,  0.9957,  9.5355,  9.5290],
        ...,
        [ 1.1191,  1.1434,  1.1534,  ...,  1.0833,  9.9821,  9.9891],
        [ 1.1202,  1.1448,  1.1548,  ...,  1.0840, 10.1809, 10.1910],
        [ 1.2251,  1.2162,  1.0976,  ...,  0.9956,  9.9003,  9.9000]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:08<00:00, 30.31it/s]


epoch 250: ARI=0.0933, CCR=0.4533, CLU=2.1881, REC=0.6671
tensor([[ 1.1206,  1.1471,  1.1678,  ...,  1.0893,  9.7213,  9.7126],
        [ 1.1199,  1.1462,  1.1668,  ...,  1.0887,  9.5960,  9.5859],
        [ 1.2392,  1.2262,  1.1081,  ...,  0.9967, 10.0713, 10.0742],
        ...,
        [ 1.1194,  1.1457,  1.1661,  ...,  1.0884,  9.5177,  9.5065],
        [ 1.1207,  1.1473,  1.1679,  ...,  1.0894,  9.7387,  9.7302],
        [ 1.2452,  1.2319,  1.1107,  ...,  0.9967, 10.6112, 10.6217]],
       device='cuda:0', grad_fn=<ClampBackward1>)
Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151669 ARI: 0.17653605
Figure saved to: figures_test/151669.png

==================== Processing Sample: 151670 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-

 22%|██▏       | 56/250 [00:01<00:05, 33.08it/s]

epoch 50: ARI=1.0000, CCR=0.5001, CLU=2.1973, REC=0.6809
tensor([[ 0.9815,  1.0935,  0.9228,  ...,  9.7568, 10.5527, 10.2093],
        [ 0.9819,  1.0883,  0.9245,  ...,  9.2410, 10.0149,  9.7369],
        [ 1.1556,  0.9736,  0.8400,  ...,  9.2289,  9.8922,  9.3007],
        ...,
        [ 0.9812,  1.0867,  0.9242,  ...,  9.0860,  9.8394,  9.5433],
        [ 0.9816,  1.0889,  0.9258,  ...,  9.5159, 10.2224,  9.9621],
        [ 1.1661,  0.9657,  0.8357,  ..., 10.3461, 11.2652, 10.4302]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 104/250 [00:03<00:04, 31.66it/s]

epoch 100: ARI=0.0483, CCR=0.5000, CLU=2.1972, REC=0.6671
tensor([[ 1.0336,  1.1222,  1.0874,  ..., 10.2811, 10.3428, 10.3646],
        [ 1.0333,  1.1203,  1.0865,  ..., 10.0104, 10.0703, 10.1208],
        [ 1.2036,  1.0590,  0.9507,  ...,  9.1463,  9.1263,  9.1358],
        ...,
        [ 1.0332,  1.1200,  1.0862,  ...,  9.9405,  9.9922, 10.0350],
        [ 1.0332,  1.1199,  1.0864,  ...,  9.9588, 10.0164, 10.0701],
        [ 1.2059,  1.0591,  0.9502,  ...,  9.3638,  9.3401,  9.3501]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 62%|██████▏   | 156/250 [00:04<00:02, 32.30it/s]

epoch 150: ARI=0.2511, CCR=0.4962, CLU=2.1972, REC=0.6621
tensor([[1.0572, 1.1563, 1.1706,  ..., 9.8104, 9.8088, 9.8337],
        [1.0574, 1.1569, 1.1712,  ..., 9.8933, 9.8891, 9.9131],
        [1.2546, 1.0751, 0.9978,  ..., 9.2446, 9.2945, 9.2765],
        ...,
        [1.0575, 1.1571, 1.1714,  ..., 9.9161, 9.9101, 9.9300],
        [1.0569, 1.1554, 1.1696,  ..., 9.6947, 9.6924, 9.7210],
        [1.2562, 1.0754, 0.9978,  ..., 9.3712, 9.4112, 9.3997]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 82%|████████▏ | 204/250 [00:06<00:01, 32.42it/s]

epoch 200: ARI=0.1851, CCR=0.4551, CLU=2.0094, REC=0.6601
tensor([[ 1.0690,  1.1853,  1.2070,  ..., 10.2744, 10.2530, 10.2596],
        [ 1.0701,  1.1888,  1.2109,  ..., 10.6980, 10.6661, 10.6745],
        [ 1.2734,  1.0757,  1.0238,  ...,  8.8451,  8.9240,  8.9026],
        ...,
        [ 1.0699,  1.1880,  1.2101,  ..., 10.6026, 10.5726, 10.5824],
        [ 1.0673,  1.1804,  1.2016,  ...,  9.7069,  9.6982,  9.7030],
        [ 1.2728,  1.0756,  1.0238,  ...,  8.8176,  8.8914,  8.8713]],
       device='cuda:0', grad_fn=<ClampBackward1>)


100%|██████████| 250/250 [00:07<00:00, 32.52it/s]


epoch 250: ARI=0.3007, CCR=0.4236, CLU=1.6003, REC=0.6591
tensor([[ 1.0758,  1.2018,  1.2266,  ..., 10.5615, 10.5587, 10.5628],
        [ 1.0767,  1.2044,  1.2296,  ..., 10.8686, 10.8595, 10.8653],
        [ 1.2862,  1.0794,  1.0345,  ...,  8.7660,  8.7292,  8.6764],
        ...,
        [ 1.0762,  1.2028,  1.2277,  ..., 10.6750, 10.6695, 10.6747],
        [ 1.0720,  1.1908,  1.2141,  ...,  9.3804,  9.4005,  9.3937],
        [ 1.2745,  1.0765,  1.0333,  ...,  8.1025,  8.0800,  8.0243]],
       device='cuda:0', grad_fn=<ClampBackward1>)
Training Finished =================<
fitting ...
  |======================================================================| 100%
Sample 151670 ARI: 0.24601961
Figure saved to: figures_test/151670.png

==================== Processing Sample: 151671 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-

 22%|██▏       | 54/250 [00:01<00:06, 29.17it/s]

epoch 50: ARI=0.0000, CCR=0.5000, CLU=2.1973, REC=0.6861
tensor([[ 1.0628,  1.0017,  0.7366,  ...,  1.1244,  1.1540, 11.3230],
        [ 1.0586,  0.9990,  0.7277,  ...,  1.1076,  1.1381, 12.1160],
        [ 0.8740,  0.8810,  0.6944,  ...,  1.0259,  0.8224, 10.4153],
        ...,
        [ 1.0554,  0.9935,  0.7347,  ...,  1.1050,  1.1367, 11.6467],
        [ 0.8870,  0.9071,  0.6509,  ...,  0.9883,  0.7677,  7.3392],
        [ 0.8849,  0.8788,  0.7058,  ...,  1.0213,  0.8299, 10.0716]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 41%|████      | 103/250 [00:03<00:05, 28.73it/s]

epoch 100: ARI=-0.0137, CCR=0.4999, CLU=2.1972, REC=0.6727
tensor([[ 1.0156,  1.0617,  0.9140,  ...,  1.0695,  1.1819,  8.9183],
        [ 1.0030,  1.0581,  0.8941,  ...,  1.0718,  1.1775, 11.4649],
        [ 1.0019,  0.9806,  0.8164,  ...,  1.1752,  0.8861, 10.4090],
        ...,
        [ 1.0045,  1.0577,  0.8980,  ...,  1.0709,  1.1765, 10.8234],
        [ 0.8637,  0.9485,  0.7391,  ...,  1.1609,  0.8202,  9.7423],
        [ 1.0162,  0.9843,  0.8383,  ...,  1.1587,  0.9049,  8.9542]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 61%|██████    | 153/250 [00:05<00:03, 28.69it/s]

epoch 150: ARI=0.0005, CCR=0.4878, CLU=2.1972, REC=0.6647
tensor([[ 1.0504,  1.0933,  1.0012,  ...,  1.0848,  1.2232,  9.5459],
        [ 1.0478,  1.0924,  0.9989,  ...,  1.0851,  1.2214,  9.7255],
        [ 1.0948,  1.0376,  0.8758,  ...,  1.2069,  0.9450, 10.0891],
        ...,
        [ 1.0436,  1.0908,  0.9952,  ...,  1.0854,  1.2181,  9.9768],
        [ 0.8899,  0.9755,  0.7860,  ...,  1.1904,  0.8932,  9.1537],
        [ 1.1071,  1.0415,  0.8820,  ...,  1.2063,  0.9494, 10.1911]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 80%|███████▉  | 199/250 [00:06<00:01, 28.99it/s]


epoch 200: ARI=0.3364, CCR=0.4504, CLU=1.9050, REC=0.6621
tensor([[ 1.0778,  1.1093,  1.0443,  ...,  1.0946,  1.2396,  9.7841],
        [ 1.0713,  1.1046,  1.0395,  ...,  1.0925,  1.2307,  9.5165],
        [ 1.1481,  1.0625,  0.9022,  ...,  1.2204,  0.9686,  9.9491],
        ...,
        [ 1.0716,  1.1063,  1.0394,  ...,  1.0944,  1.2351, 10.0064],
        [ 0.9068,  0.9834,  0.7922,  ...,  1.2164,  0.9198, 10.1377],
        [ 1.1473,  1.0623,  0.9010,  ...,  1.2217,  0.9680, 10.0444]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151671 ARI: 0.53574661
Figure saved to: figures_test/151671.png

==================== Processing Sample: 151672 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) ======================

 22%|██▏       | 56/250 [00:01<00:06, 29.82it/s]

epoch 50: ARI=1.0000, CCR=0.5001, CLU=2.1973, REC=0.6781
tensor([[ 0.6657,  1.1230,  1.0706,  ...,  1.0537,  1.1730, 11.1005],
        [ 0.6594,  1.1236,  1.0618,  ...,  1.0508,  1.1713, 11.3625],
        [ 0.9468,  0.9974,  0.8359,  ...,  0.8618,  1.0908, 10.1397],
        ...,
        [ 0.6284,  1.1181,  0.9859,  ...,  1.0268,  1.1483, 10.8672],
        [ 0.6752,  1.1213,  1.0802,  ...,  1.0549,  1.1748, 10.7882],
        [ 0.9553,  0.9948,  0.8386,  ...,  0.8599,  1.0839, 10.7847]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 42%|████▏     | 106/250 [00:03<00:04, 30.28it/s]

epoch 100: ARI=0.0541, CCR=0.5000, CLU=2.1972, REC=0.6639
tensor([[ 0.8686,  1.1812,  1.1253,  ...,  1.1303,  1.1725,  8.8521],
        [ 0.8694,  1.1815,  1.1273,  ...,  1.1321,  1.1737,  8.8567],
        [ 0.8975,  1.0284,  1.0238,  ...,  0.9601,  1.1124, 10.2343],
        ...,
        [ 0.8478,  1.1756,  1.0806,  ...,  1.0921,  1.1467,  8.9636],
        [ 0.8750,  1.1801,  1.1340,  ...,  1.1375,  1.1762,  8.5869],
        [ 0.9102,  1.0249,  1.0352,  ...,  0.9718,  1.1185, 10.1676]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 62%|██████▏   | 154/250 [00:05<00:03, 30.73it/s]

epoch 150: ARI=0.1230, CCR=0.4982, CLU=2.1972, REC=0.6624
tensor([[ 0.9243,  1.2850,  1.1757,  ...,  1.0753,  1.2011, 15.6684],
        [ 0.8925,  1.2837,  1.1073,  ...,  1.0092,  1.1569, 14.8058],
        [ 0.8313,  0.9580,  1.0870,  ...,  0.9231,  1.1258, 13.5774],
        ...,
        [ 0.8426,  1.2543,  0.9802,  ...,  0.8925,  1.0626, 10.5362],
        [ 0.9203,  1.2764,  1.1581,  ...,  1.0609,  1.1876, 14.4536],
        [ 0.8452,  0.9628,  1.0808,  ...,  0.9309,  1.1167, 10.7857]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 80%|███████▉  | 199/250 [00:06<00:01, 29.95it/s]


epoch 200: ARI=0.3751, CCR=0.4346, CLU=2.0876, REC=0.6562
tensor([[ 1.0202,  1.2689,  1.1866,  ...,  1.1160,  1.2021, 10.3503],
        [ 1.0069,  1.2689,  1.1586,  ...,  1.0889,  1.1890, 10.3039],
        [ 0.8779,  1.0098,  1.1683,  ...,  0.9977,  1.1238,  9.7218],
        ...,
        [ 0.9363,  1.2665,  1.0160,  ...,  0.9504,  1.1181, 10.0187],
        [ 1.0303,  1.2612,  1.2043,  ...,  1.1350,  1.2069,  9.7866],
        [ 0.8794,  1.0094,  1.1686,  ...,  0.9993,  1.1241,  9.5503]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151672 ARI: 0.66696117
Figure saved to: figures_test/151672.png

==================== Processing Sample: 151673 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) ======================

 22%|██▏       | 56/250 [00:01<00:05, 32.50it/s]

epoch 50: ARI=0.2741, CCR=0.4146, CLU=2.4960, REC=0.7471
tensor([[1.1354, 0.7349, 1.0651,  ..., 1.0223, 1.4315, 1.0942],
        [0.9846, 1.1819, 1.0387,  ..., 1.1998, 2.2382, 0.8336],
        [0.9739, 1.3142, 1.0894,  ..., 1.2083, 2.0249, 0.8572],
        ...,
        [0.9817, 1.2559, 1.0782,  ..., 1.2348, 2.1158, 0.8374],
        [0.9773, 1.3103, 1.0862,  ..., 1.2124, 2.0826, 0.8500],
        [1.1247, 0.7551, 1.0772,  ..., 1.0005, 1.3818, 1.0709]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 40%|███▉      | 99/250 [00:03<00:04, 32.05it/s]


epoch 100: ARI=0.3793, CCR=0.3903, CLU=1.8351, REC=0.7307
tensor([[1.1400, 0.7847, 1.1187,  ..., 1.0719, 1.4462, 1.1815],
        [1.0949, 1.1392, 1.0135,  ..., 1.1553, 1.7821, 0.9803],
        [1.0283, 1.5773, 1.0847,  ..., 1.2188, 2.5366, 0.9555],
        ...,
        [1.0633, 1.3772, 1.0487,  ..., 1.1962, 2.2231, 0.9644],
        [1.0318, 1.5733, 1.0809,  ..., 1.2180, 2.5357, 0.9555],
        [1.1450, 0.7486, 1.0981,  ..., 1.0525, 1.3478, 1.1554]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151673 ARI: 0.33208391
Figure saved to: figures_test/151673.png

==================== Processing Sample: 151674 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 22%|██▏       | 56/250 [00:01<00:06, 32.30it/s]

epoch 50: ARI=0.0034, CCR=0.4980, CLU=2.5650, REC=0.8075
tensor([[1.0168, 0.8550, 1.1941,  ..., 1.0910, 0.9063, 1.6826],
        [1.3472, 0.7669, 0.9524,  ..., 1.2037, 1.3348, 2.4311],
        [1.3057, 0.7975, 0.9653,  ..., 1.2832, 1.3221, 2.2779],
        ...,
        [1.3288, 0.7798, 0.9499,  ..., 1.2532, 1.3409, 2.3630],
        [1.3091, 0.7902, 0.9575,  ..., 1.2820, 1.3313, 2.2990],
        [1.1474, 0.9689, 1.0515,  ..., 1.0392, 0.9953, 1.3531]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 40%|███▉      | 99/250 [00:03<00:04, 32.26it/s]


epoch 100: ARI=0.6236, CCR=0.4196, CLU=2.4715, REC=0.7902
tensor([[1.0261, 1.0437, 1.1491,  ..., 1.0595, 0.9568, 1.6942],
        [1.3292, 0.9320, 1.0789,  ..., 1.1998, 1.2851, 2.2489],
        [1.3336, 0.9205, 1.0759,  ..., 1.2363, 1.3061, 2.4044],
        ...,
        [1.3524, 0.9235, 1.0812,  ..., 1.2261, 1.3114, 2.4088],
        [1.3444, 0.9230, 1.0787,  ..., 1.2284, 1.3068, 2.3969],
        [1.3328, 0.9398, 1.0793,  ..., 1.1758, 1.2718, 2.1843]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151674 ARI: 0.30233194
Figure saved to: figures_test/151674.png

==================== Processing Sample: 151675 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 22%|██▏       | 56/250 [00:01<00:05, 32.47it/s]

epoch 50: ARI=0.7920, CCR=0.4845, CLU=2.5649, REC=0.6954
tensor([[1.0702, 0.8262, 0.9723,  ..., 0.9545, 1.0316, 1.1626],
        [1.1232, 0.7551, 0.9713,  ..., 0.9164, 1.0907, 1.2799],
        [0.8971, 0.7599, 1.3907,  ..., 1.4122, 0.9747, 2.0311],
        ...,
        [0.8971, 0.7600, 1.3901,  ..., 1.4111, 0.9747, 2.0327],
        [0.9130, 0.7651, 1.3661,  ..., 1.4440, 0.9354, 2.0380],
        [0.8943, 0.7603, 1.3926,  ..., 1.4246, 0.9652, 2.0387]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 40%|███▉      | 99/250 [00:03<00:04, 32.39it/s]


epoch 100: ARI=0.3926, CCR=0.4025, CLU=2.0144, REC=0.6782
tensor([[1.1242, 0.8741, 0.9363,  ..., 1.0110, 1.1224, 1.2192],
        [1.1619, 0.8513, 0.9199,  ..., 1.0102, 1.1546, 1.2627],
        [1.0306, 0.9447, 1.3876,  ..., 1.3017, 1.0281, 1.9322],
        ...,
        [1.0306, 0.9447, 1.3876,  ..., 1.3018, 1.0281, 1.9325],
        [1.0406, 0.9414, 1.3692,  ..., 1.3128, 1.0125, 1.9086],
        [1.0324, 0.9439, 1.3875,  ..., 1.3060, 1.0253, 1.9351]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151675 ARI: 0.33002865
Figure saved to: figures_test/151675.png

==================== Processing Sample: 151676 ====================
Preprocessing starting according to CSMVL description...
Selecting top 3000 HVGs...
Normalizing total counts to 10,000...
Scaling and clipping at threshold 10...
Training Start (Enhanced 3-View with CCR) =========================>


 22%|██▏       | 56/250 [00:01<00:05, 33.02it/s]

epoch 50: ARI=0.3243, CCR=0.4942, CLU=2.5650, REC=0.7197
tensor([[1.0851, 0.9758, 0.8812,  ..., 1.0804, 1.0009, 1.3663],
        [1.0737, 0.9815, 0.9021,  ..., 1.0649, 0.9950, 1.3198],
        [1.0710, 0.8596, 1.3376,  ..., 0.9067, 1.1304, 1.7774],
        ...,
        [1.0727, 0.8591, 1.3391,  ..., 0.9072, 1.1314, 1.7780],
        [1.0756, 0.8509, 1.3498,  ..., 0.9072, 1.1365, 1.7955],
        [1.0646, 1.0011, 0.9132,  ..., 1.0731, 0.9894, 1.2917]],
       device='cuda:0', grad_fn=<ClampBackward1>)


 40%|███▉      | 99/250 [00:03<00:04, 32.39it/s]


epoch 100: ARI=0.5308, CCR=0.4074, CLU=2.4257, REC=0.7063
tensor([[1.1547, 1.1094, 0.8875,  ..., 1.1034, 1.1001, 1.4083],
        [1.1459, 1.1054, 0.8941,  ..., 1.0975, 1.0949, 1.3858],
        [1.0786, 1.0015, 1.3600,  ..., 1.0077, 1.1258, 1.8270],
        ...,
        [1.0788, 1.0015, 1.3606,  ..., 1.0077, 1.1260, 1.8285],
        [1.0825, 0.9998, 1.3727,  ..., 1.0097, 1.1289, 1.8573],
        [1.1370, 1.1019, 0.9004,  ..., 1.0944, 1.0915, 1.3639]],
       device='cuda:0', grad_fn=<ClampBackward1>)
fitting ...
  |======================================================================| 100%
Sample 151676 ARI: 0.34195952
Figure saved to: figures_test/151676.png

==================== Final Results ====================
ARI per slice: [0.39271, 0.27057, 0.39328, 0.36448, 0.17654, 0.24602, 0.53575, 0.66696, 0.33208, 0.30233, 0.33003, 0.34196]
Mean ARI: 0.3627
Median ARI: 0.3370
